### ISSUE TITLE
Question about phase 1 mapper

### ISSUE THREAD

**Issue by yenchenlin** [HappyStorm/Introduction-to-Massive-Data-Analysis#1]
What is [this line](https://github.com/HappyStorm/Introduction-to-Massive-Data-Analysis/blob/master/HW2_Page%20Rank/java/phase1_mapper.java#L18) doing ?

Will input file contain "#" ?

**Comment by yenchenlin** [comment]
I see why 😄

**Comment by HappyStorm** [comment]
Good Job ><
